name: fyp_new
description: "A new Flutter project."
publish_to: 'none'
version: 0.1.0

environment:
  sdk: '>=3.2.3 <4.0.0'

dependencies:
  permission_handler: ^11.1.0
  provider: ^6.1.1
  flutter_local_notifications: ^9.6.0
  geolocator: ^9.0.2
  fl_chart: ^0.66.0
  app_settings: ^4.2.0
  open_settings: ^2.0.2
  flutter_beacon: ^0.5.1
  get: ^4.3.6
  cupertino_icons: ^1.0.6

  flutter:
    sdk: flutter

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0

flutter:
  uses-material-design: true
