name: fyp_new
description: "A new Flutter project."
publish_to: 'none'
version: 0.1.0

environment:
  sdk: '>=3.2.3 <4.0.0'

dependencies:
  permission_handler: ^11.1.0
  flutter_blue_plus: ^1.31.7
  intl: ^0.17.0
  flutter_local_notifications: ^9.6.0
  geolocator: ^9.0.2
  fl_chart: ^0.66.0
  flutter_echarts: ^2.5.0
  syncfusion_flutter_charts: ^21.1.4
  beacons_plugin: ^2.0.8
  app_settings: ^4.2.0
  open_settings: ^2.0.2
  flutter_beacon: ^0.5.1
  get: ^4.3.6
  cupertino_icons: ^1.0.6
  webview_flutter: ^4.4.4
  http: ^1.1.2
  rxdart: ^0.27.7
  uuid: ^4.2.2

  flutter:
    sdk: flutter

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0

flutter:
  uses-material-design: true
